### ISSUE TITLE
SF#444 Fails to build with Proj 5.0.0

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#230]
@sebastic writes:

In preparation of the upcoming Proj 5.0.0 release, the pdl Debian package was rebuilt with Proj 5.0.0-rc2. Unfortunately it failed to build:

```
x86_64-linux-gnu-gcc -c  "-I/build/pdl-2.018/Basic/Core" "-I/usr/include" -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -O2 -fdebug-prefix-map=/build/pdl-2.018=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -DVERSION=\"1.32\" -DXS_VERSION=\"1.32\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.26/CORE"   Proj.c
In file included from Proj.xs:37:0:
/usr/include/projects.h:161:40: error: conflicting types for 'UV'
 typedef struct { double u, v; }        UV;
                                        ^~
In file included from Proj.xs:22:0:
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:1655:16: note: previous declaration of 'UV' was here
 typedef UVTYPE UV;
                ^~
```

https://sourceforge.net/p/pdl/bugs/444/

**Comment by sebastic** [comment]
Note that PDL no longer fails to build with Proj 5.0.0, but still needs to be updated to use the new API (because the old APIs will be removed in the Proj 6.0 & Proj 7.0).

**Comment by mohawk2** [comment]
@sebastic Thanks for the update!

Btw, I failed to copy over this at the end of your bug report, the NEWS file from Proj 5.0.1 that spells out what to do: https://github.com/OSGeo/proj.4/blob/master/NEWS

Do you feel like having a go at this? I'm hoping it wouldn't involve much more than a `#if[def]`/`#else` block for Proj version?

**Comment by sebastic** [comment]
I'm mostly a package maintainer, and not a very good C programmer.

Because I maintain most of the GIS packages in Debian (proj, geotiff, gdal, netcdf etc), and PDL and some of its related modules (e.g. PDL::NetCDF) are reverse dependencies of those GIS package I've started to help maintain the pdl package in Debian because the original maintainer doesn't have time for it any more.

I might be able to hack something together based on the changes GRASS and GDAL made to support the PROJ 5.0 API, but it will be entirely unsupported and without any guarantee of correctness. If there is no one else to work on the PROJ support in PDL, I might be willing to do this when I find the time, but I don't consider myself a good candidate for this task.

**Comment by mohawk2** [comment]
In my experience, contributor caution and humility generally tracks closely with the excellence of their contribution. If you were able to knock together something, even just spelling out what CPP macros one would use to do the `#if`, that would already be highly useful. I suspect the hardest bit would be figuring how to make Travis make available the right Proj version, and that can be special-cased in the same spirit as Zaki's gcc -> clang work.

**Comment by forskning** [comment]
https://proj4.org/development/migration.html

Version 4 to 5 API Migration

**Comment by mohawk2** [comment]
As noted on #283 I will now close this issue since it is fixed! @sebastic This hasn't been released on CPAN yet as there are some other changes I want to finish first (loop-fusion and generating bespoke PDL operations on forcing lazy-evaluated functions). But are there any further issues related to PDL and PROJ you can highlight for me while my head is in that game?

**Comment by sebastic** [comment]
As long as the PROJ support via Alien::proj remains optional there shouldn't be any issues for the pdl Debian package (as Alien::proj is not packaged).

Regarding modern PROJ, you'll have different results depending on whether the datum grids are available either by having proj-data unpacked locally or enabled the CDN in proj.ini or via the PROJ_NETWORK=ON env var. That's a gotcha you should be aware (e.g. when implementing transformation tests).

**Comment by mohawk2** [comment]
So far our binding has been very agnostic of these things, since we don't build PROJ ourselves, just consume it via Alien::proj. Given that our usage of that is more or less just to get its `cflags` and `libs`, and for a system install (as on my Ubuntu box here) those are respectively empty-string and `-lproj`, what do you think about having a Debian patch that just ripped out the few Alien::proj references and replaced them with those hardcoded strings?

**Comment by sebastic** [comment]
Using pkg-config should suffice to get the flags for PROJ.

PROJ will switch to CMake in the upcoming 9.0.0 release scheduled for March 2022, that build got fixed some time ago to also install proj.pc (on UNIX & MinGW), so that be good for the foreseeable future.

**Comment by mohawk2** [comment]
That does sound sensible, though CPAN PDL won't use it since I'd like to retain the capability for users to use the Alien system. Am I right that Debian would be able to utilise the pkg-config in its PDL package-building to support PROJ?

**Comment by sebastic** [comment]
Yes, the Debian package build can use pkg-config (instead of Alien::proj).

**Comment by mohawk2** [comment]
Superb, thank you! Do you folks routinely monitor CPAN releases (or maybe you're subscribed to the pdl-devel list?), or would it help you if I send an email on the next release?

**Comment by sebastic** [comment]
The Debian package monitors https://metacpan.org/release/PDL for new versions, see:

 https://salsa.debian.org/perl-team/modules/packages/pdl/-/blob/master/debian/watch
 https://qa.debian.org/cgi-bin/watch?pkg=pdl

Due to the high frequency of releases it is only updated once a month now, though.

**Comment by mohawk2** [comment]
Thank you for the info! And once a month makes lots of sense. Let us know if there's anything we can do to automate things to make it easier for you.
